- name: Install utilities packages (Debian)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  loop: [ "{{ debian_utils_pkg_list }}" ]
