- name: OS Family
  debug: msg="{{ ansible_os_family }}"
- name: Distribution
  debug: msg="{{ ansible_distribution }}"
- name: Distribution major version
  debug: msg="{{ ansible_distribution_major_version }}"
- name: Distribution version
  debug: msg="{{ ansible_distribution_version}}"
- name: Test requirement
  debug: msg="new test req"
