---
# tasks file for update-os
- name: Import Os update role (Redhat)
  import_tasks: update_os-redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'
- name: Import Os update role (Debian)
  import_tasks: update_os-debian.yml
  when: ansible_facts['os_family']|lower == 'debian' or ansible_facts['os_family']|lower == 'osmc'

- name: Reboot host
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: update_os_reboot_required.stat.exists
