---
- name: Install packages (Redhat)
  ansible.builtin.yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  loop: "{{ set_applications_settings.applications.packages if set_applications_settings.applications.packages is iterable and set_applications_settings.applications.packages is not string else []}}"
