---
# tasks file for nordvpn
- name: Import Nordvpn package installation role (Redhat)
  import_tasks: configure_nordvpn-redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'  
- name: Import Nordvpn package installation role (Debian)
  import_tasks: configure_nordvpn-debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

