---
# tasks file for install-utils
- name: Import packages installation tasks (Redhat)
  import_tasks: install_utils-redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Import packages installation tasks (Debian)
  import_tasks: install_utils-debian.yml
  when: ansible_facts['os_family']|lower == 'debian' or ansible_facts['os_family']|lower == 'osmc' or ansible_facts['os_family']|lower == 'libreelec'
